[phases.setup]
nixPkgs = ['nodejs_18', 'chromium', 'nss', 'nspr', 'atk', 'cups', 'libdrm', 'gtk3', 'pango', 'cairo', 'xorg.libX11', 'xorg.libXcomposite', 'xorg.libXdamage', 'xorg.libXext', 'xorg.libXfixes', 'xorg.libXrandr', 'mesa', 'libxkbcommon', 'alsa-lib']

[phases.install]
cmds = ['npm install']

[start]
cmd = 'node src/server.js'
