name: Deploy para Servidor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 46.225.150.104
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/liga-urologia
            git fetch origin main
            git reset --hard origin/main
            npm install --production
            pm2 delete liga-urologia || true
            pm2 start /var/www/liga-urologia/src/server.js --name liga-urologia
            pm2 save
            echo "Deploy concluído!"
